### ISSUE TITLE
¡Hola!

### ISSUE THREAD

**Issue by R-CoderDotCom** [fabarrios/ProbEstad2021#1]
¡Hola! Casualmente encontré que enlazas a mi web desde tu curso ¡Muchas gracias! Abro este issue porque veo que la agregas como material en inglés, pero también está disponible todo el material en español: https://r-coder.com/introduccion-r/

Otra página de la web que puede resultar de interés a tus alumnos es: https://r-coder.com/curso-r/ donde se recogen de de forma ordenada en secciones contenidos introductorios. Para acceder a los artículos de cada sección tan solo hay que hacer click en el nombre de la sección para que se abran los contenidos. Estos contenidos también son accesibles en cualquier momento desde el menú que aparece poniendo el ratón sobre "Aprende R".

Dentro de poco publicaré una nueva web especializada en gráficos de R con muchas funcionalidades, también en español y en inglés. Comentaré el lanzamiento en redes sociales (https://twitter.com/RCoderWeb).

Un saludo y muchas gracias por recomendar mi página.

**Comment by fabarrios** [comment]
Muchas gracias por tu mensaje, el material está muy bueno y de gran utilidad. Lo he dejado en inglés para que los estudiantes también hagan un esfuerzo para trabajar en inglés. Pero agradezco mucho tu mensaje, ya que el semenstre entrante volveré a enseñar en la ENESj-UNAM y voy a poner tus páginas como material de consulta.
Gracias y sigue con el buen trabajo. Un saludo desde México.
